### ISSUE TITLE
[FEAT] 유저 정보 조회 api (햄버거 메뉴)

### ISSUE THREAD

**Issue by biiit4894** [jobofbrothers-sobok/SOBOK-SERVER#21]
## 📌  Feature Issue

- 로그인 후 햄버거 메뉴 클릭 시 고객 정보를 조회하는 api입니다.

## 📝  To-do

- [x] 고객 유저 이름 조회
  - [x] - INVALID TOKEN 에러가 계속 발생하여 auth 재설정이 필요합니다.  
- [x] 점주 유저 이름 조회
- [ ] 최근 검색어 조회
