### ISSUE TITLE
[FEAT] 점주 매장 정보 등록/수정 api 구현

### ISSUE THREAD

**Issue by biiit4894** [jobofbrothers-sobok/SOBOK-SERVER#26]
## 📌  Feature Issue

- 점주 유저가 점주 페이지에서 매장 정보를 등록 및 수정하는 api를 구현합니다. 

## 📝  To-do

- [x] 점주 매장정보 등록 및 수정 api
- [x] 매장정보 등록 시 점주에게 storeId 부여되도록
- [x] req.user.id 받아올 수 있도록 jwt token 관련 로직 수정
- [x] 매장정보 category : string array
