### ISSUE TITLE
[FEAT] 스탬프 적립 관련 api 구현

### ISSUE THREAD

**Issue by biiit4894** [jobofbrothers-sobok/SOBOK-SERVER#36]
## 📝  To-do

- [x] 유저 생성번호 조회 api
- [x] 점주 스탬프 적립 승낙 api
- [x] 유저 스탬프 적립내역 조회 api
- [x] 소복 스탬프 참여 매장 조회 api
