### ISSUE TITLE
[FEAT] 점주 마이페이지 관련 기능 구현

### ISSUE THREAD

**Issue by biiit4894** [jobofbrothers-sobok/SOBOK-SERVER#57]
## 📌  Feature Issue

- 점주 마이페이지에서 접근할 수 있는 기능들을 위한 api를 구현합니다.

## 📝  To-do

- [x] 담당자 정보수정 api
- [x] 매장 정보 등록/수정 api
  - [x] 이미지 등록 가능하도록 수정
  - [x] category string array 필드 form data에 한꺼번에 전송 안되는 문제 해결
- [x] 매장 소식 등록 api 
  - [x] 이미지 등록 가능하도록 수정
- [x] 매장 메뉴 등록 api
  - [x] 이미지 등록 가능하도록 수정 
- [x] 스토어 상품 등록 api
  - [x] 이미지 등록 가능하도록 수정 
- [x] 소복 매니저 신청 api
