### ISSUE TITLE
[FEAT] 고객, 점주 회원정보 수정 api 구현

### ISSUE THREAD

**Issue by biiit4894** [jobofbrothers-sobok/SOBOK-SERVER#9]
## 📌  Feature Issue

- 고객과 점주 유저의 회원정보 수정 api를 구현합니다.

## 📝  To-do

- [x] 고객 유저 회원정보 수정 api 구현
  - [x] 프로필 이미지 등록 가능하도록 DB에 필드 추가
- [x] 점주 유저 회원정보 수정 api 구현
  - [x] 담당자 프로필 이미지 등록 가능하도록 DB에 필드 추가
